grpc:
  server:
    port: 59091

spring:
  main:
    banner-mode: OFF

logging:
  level:
    org:
      zalando:
        logbook:
          Logbook: TRACE

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  topics:
    hub-events: telemetry.hubs.v1
    sensor-events: telemetry.sensors.v1